name: INTEGRATION CD DISTRIBUTION API

on:
  pull_request:
    types: [opened,reopened,synchronize,labeled]

jobs:
  distribution_api_integration:
    name: Distribution API Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: contains(github.event.pull_request.labels.*.name, 'integration-deployment')

    steps:
      - name: Checkout the repository üéÅ
        uses: actions/checkout@v2

      - name: Setting up PHP ‚öôÔ∏è
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml

      - name: Installing Dependencies üß©
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Authenticating to google üîê
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}

      - name: Setting up google Cloud SDK üí≥
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Setting up github token... üß®
        run: |
          mv config/parameters.yaml.dist config/parameters.yaml 
#          sed -i 's/github_token.*/github_token\:\ ${{ secrets.GITHUB_TOKEN }}/' config/parameters.yaml
#        env:
#          token: ${{secrets.TOKEN}}

      - name: Checking out the repositories... üîç
        run: ./bin/console checkRepos
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Checking Native Modules... üë∑
        run: ./bin/console downloadNativeModuleMainClasses
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Downloading install php files... üîç
        run: ./bin/console downloadPrestaShopInstallVersions
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Generating json files... üë∑
        run: ./bin/console generateJson
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Pushing json files... üî•
        run: gsutil cp -r public/json/* gs://distribution-api-artifacts/
