name: INTEGRATION CRON DISTRIBUTION API

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '57 16 * * *'

jobs:
  distribution_api_integration:
    name: Distribution API Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout the repository ğŸ
        uses: actions/checkout@v2

      - name: Setting up PHP âš™ï¸
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml

      - name: Installing Dependencies ğŸ§©
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Authenticating to google ğŸ”
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}

      - name: Setting up google Cloud SDK ğŸ’³
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Setting up github token... ğŸ§¨
        run: |
          mv config/parameters.yaml.dist config/parameters.yaml 
          sed -i 's/github_token.*/github_token\:\ ${{ secrets.GITHUB_TOKEN }}/' config/parameters.yaml
        env:
          token: ${{secrets.TOKEN}}

      - name: Checking out the repositories... ğŸ”
        run: ./bin/console checkRepos

      - name: Checking Native Modules... ğŸ‘·
        run: ./bin/console downloadNativeModuleMainClasses

      - name: Downloading install php files... ğŸ”
        run: ./bin/console downloadPrestaShopInstallVersions

      - name: Generating json files... ğŸ‘·
        run: ./bin/console generateJson

      - name: Pushing json files... ğŸ”¥
        run: gsutil cp -r public/json/* gs://distribution-api-artifacts/
