name: INTEGRATION CRON DISTRIBUTION API

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 09-19 * * *'

jobs:
  distribution_api_integration:
    name: Distribution API Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout the repository üéÅ
        uses: actions/checkout@v2

      - name: Setting up PHP ‚öôÔ∏è
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml

      - name: Installing Dependencies üß©
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Authenticating to google üîê
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}

      - name: Setting up google Cloud SDK üí≥
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Checking out the repositories... üîç
        run: ./bin/console checkRepos
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Checking Native Modules... üë∑
        run: ./bin/console downloadNativeModuleMainClasses
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Downloading install php files... üîç
        run: ./bin/console downloadPrestaShopInstallVersions
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Updating modules' yaml config file... ‚¨ÜÔ∏è
        run: ./bin/console updateModuleConfigFiles
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Generating json files... üë∑
        run: ./bin/console generateJson
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Pushing json files... üî•
        run: gsutil cp -r public/json/* gs://distribution-api-artifacts/
